### ISSUE TITLE
The titles in example_recipe.md are reversed.

### ISSUE THREAD

**Issue by MaxwellGBrown** [clagraff/recipes#33]
Below I've cut & pasted the contents of `example_recipe.md` as they are now.

The title `### Cooking Instructions`` is a lower level header than any "sections" of the recipe (e.g. `## Cooking the First Part`, `## Cooking the Second Part`).

The way it's displayed right now suggests that **Cooking Instructions** is a sub-section of **Ingredients**.

<hr/>

# Name of Meal Here

[Original Recipe](https://link.com/to-recipe-onlne-if-applicable)

## Ingredients

* 2 tbsp of love
* 3 cups of happyness
* 1 2/3 zest of encouragement
* `optional` 10 tsp of hardwork

## Cooking the first part

* Mix all the dry seasonings.
* Prepare the thing to roast the other thing.
* Do the thing.

## Cooking the second part, Part II.

* Do more stuff.
* `optional` Complete other thing.
* Add stuff; be done.

**Comment by clagraff** [comment]
thanks. good catch.

**Comment by clagraff** [comment]
Fixed. Also added `Preparation` section
